## input number from user w,r,a (task1)

In [1]:

fairy_file = open("numbers.txt", "w")

#get input from user max 4 numbers
number1 = (input("Your 1st number is:"))
number2 = (input("Your 2nd number is:"))
number3 = (input("Your 3rd number is:"))
number4 = (input("Your last number is:"))

fairy_file.write(number1 + "\n")
fairy_file.write(number2 + "\n")
fairy_file.write(number3 + "\n")
fairy_file.write(number4 + "\n")

fairy_file.close()

In [2]:
fairy_file = open("numbers.txt", "a")
fairy_file.write("My Birthday is on 22/11!")
fairy_file.close()

# mark_grade (task2)

In [9]:
def mark_grade (mark):
    if mark >=85 and mark<=100:
        return "A"
    elif mark >=70 and mark<85:
        return "B"
    elif mark >= 60 and mark < 70:
        return "C"
    elif mark >= 50 and mark < 60:
        return "D"
    elif mark >= 40 and mark < 50:
        return "E"
    elif mark >= 0 and mark < 40:
        return "F"
    else:
        return "Input not valid, key in the correct mark"

In [38]:
target_grade = input(str("Enter your target grade between A and F: "))
mark=input("Enter the actual student's mark: ")

grade = mark_grade(int(mark))
print ('Your grade is: ' + grade)

#xtar = ['A','B','C','D','E','F']

if target_grade == 'A' or 'B' or 'C' or 'D' or 'E' or 'F':

    if grade != "Input not valid, key in the correct mark" :

        if target_grade == grade:
            print('You have achieved your targetted grade. Good Effort !')
        elif target_grade < grade:
            print('You have achieved less than your targetted grade. Work harder. Do not give up!')
        elif target_grade > grade and target_grade < 'G':
            print ('You have achieved higher than your targetted grade. Bravo! ')
        else:
            print("Your target grade is invalid")

Your grade is: C
You have achieved higher than your targetted grade. Bravo! 


## Numpy (task 3)

In [39]:
import numpy as np

In [43]:
# 1- create 1D array of numbers from 0 to 9

x = np.arange(0, 10)
print("Array from 0 to 10: " , x)


Array from 0 to 10:  [0 1 2 3 4 5 6 7 8 9]


In [49]:
# 2- Create a 3x3 Numpy array of all Boolean value Trues
tru = np.arange(1,10).reshape(3,3)
bool_tru = np.array(tru, dtype= bool)
print(bool_tru)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [51]:
tru2 = np.ones(9).reshape(3,3)
truee = np.array(tru2, dtype = bool)
print(truee)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [61]:
#3 - Extract all odd numbers from array of 1-10 
arr1 = np.arange(1,11,1)
oddnum = arr1[arr1 % 2 == 1]
print(oddnum)

[1 3 5 7 9]


In [63]:
#4 - Replace all odd numbers from array of 1-10 with -1

replace = np.where(arr1 % 2 == 0, arr1,-1)
print(replace)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [55]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
#5- Convert a 1D array to a 2D array with 2 rows

convert = np.arange(1,21,1)
aftercon = convert.reshape(10,2)
print(aftercon)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [73]:
# Check item 2D array
aftercon[1,0]

3

In [77]:
# - 6 

a = np.array([[5,6],[7,8]]) 
b = np.array([[17,18],[19,20]]) 
c = np.dot(a,b)
print (c)
print ("\n Sum of a : ", np.sum(a))
print ("\n Sum of b : ", np.sum(b))
print ("\n Sum of b : ", np.sum(a+b))

[[199 210]
 [271 286]]

 Sum of a :  26

 Sum of b :  74

 Sum of b :  100


In [78]:
#Extension 1

a = np.array([1,2,3])
#desired output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
np.r_[np.repeat(a, 3), np.tile(a, 3)] #concatenate on one axis

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [80]:
#Extension - 2 - In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) remove all repeating items present in array b

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])

newb = np.setdiff1d(b,a)
print(newb)

[6 7 8 9]


In [86]:
#Extension 3 - Get all items between 3 and 7 from a and b and sum them together

a_ = a[2:]
b_ = b[:4]
asum = np.sum(a_)
bsum = np.sum(b_)
print(np.sum(asum+bsum))

34
